[42기 강신혜] Add: 상세페이지 조회 API 구현
wecode-bootcamp-korea/42-1st-Naweki-backend pull request #12
Opened 2023-02-14 08:18 UTC by ksh0123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 상세페이지 조회 API 구현

<br />

## :: 구현 사항 설명
- API 호출 시 아래 데이터 반환
    - 제품 상위 제품이름
    - 제품 하위 제품이름
    - 가격
    - 메인 카테고리
    - 서브 카테고리
    - 색상
    - 스타일코드
    - 할인률
    - 생성날짜
    - 이미지별 URL
    - 제품 상세설명
    - 사이즈별 수량
    - 리뷰 (제목, 본문, 이미지 ) 

<br />

## :: 테스트 결과 이미지
1. 응답 메시지
`{
    "product": {
        "id": 1,
        "name": "나이키 에어 포스 1 '07 프레시",
        "subName": "남성 신발",
        "price": "169000.00",
        "thumbnailImage": "thumbnail.image",
        "subCategory": "라이프스타일",
        "mainCategory": "신발",
        "description": "test desc 1",
        "currentColor": "브라운",
        "styleCode": "DM0211-100",
        "discountRate": null,
        "createdAt": "2023-02-10T07:15:15.000Z",
        "imageUrl": "test.url,test.url/2,test.url/3,test.url/4,test.url/5",
        "stock": [
            {
                "size": "270",
                "count": "7"
            },
            {
                "size": "280",
                "count": "4"
            }
        ],
        "reviews": [
            {
                "id": 2,
                "name": "Lisa Bowman",
                "title": "highly recommend",
                "rating": 5,
                "createdAt": "2023-02-13 19:46:35.000000",
                "description": "Great shoe!"
            },
            {
                "id": 3,
                "name": "Lisa Bowman",
                "title": "happy customer",
                "rating": 5,
                "createdAt": "2023-02-13 19:47:19.000000",
                "description": "One of the most comfortable running shoes I have ever used"
            },
            {
                "id": 4,
                "name": "Lisa Bowman",
                "title": "happy customer",
                "rating": 5,
                "createdAt": "2023-02-13 19:47:23.000000",
                "description": "One of the most comfortable running shoes I have ever used"
            },
            {
                "id": 5,
                "name": "Lisa Bowman",
                "title": "Awesome shoe",
                "rating": 5,
                "createdAt": "2023-02-13 19:47:59.000000",
                "description": "One of the most comfortable running shoes I have ever used"
            }
        ]
    }
}`

<img width="688" alt="image" src="https://user-images.githubusercontent.com/122417190/218677386-082920d9-01c4-4364-b9e6-62ddfa20d6d9.png">

<br />

## :: 기타 질문 및 특이 사항
- 아래 코드는 원래 GROUP_CONCAT 대신 JSON_ARRAYAGG 함수를 썼는데, 결과가 스트링으로 변환되는 문제가 발생해서 프론트단에서 선호하는 포맷으로 반환하기 위해 group_concat으로 적용하여 해결했습니다. 추후에 arrayagg 함수를 사용했을 때 스트링으로 반환됐을 때, 이 현상에 어떻게 접근하는 것이 좋을까요? json_parse, json_unquote 등 수동으로 홑따옴표를 제거하는 방식은 적용되지 않는 걸 확인했습니다..
    - productDao.js -> getDetails 함수 -> line 99 "GROUP_CONCAT(pi.url) as imageUrl"

2023-02-14 12:43 UTC, kyeongraekim requested changes
간단한 수정사항 아래와 같이 남겨드립니다!~

2023-02-14 12:43 UTC, kyeongraekim commented on classes/product.js
> +  }
다음의 내용처럼 수정하여 if-else 블록을 탈피한 하나의 로직으로 변경할 수  있겠네요!

```javascript

keyCheck() {
    return Boolean(this.name && this.price && this.description && this.styleCode);
  }

2023-02-14 12:43 UTC, kyeongraekim commented on controllers/productController.js
> +const getDetails = catchAsync(async (req, res) => {
- 변수명에는 getProductDetails 등과 같이 정확한 어떤 리소스에 대한 get 요청인지가 더 명확히 드러나면 좋습니다!

2023-02-14 12:43 UTC, kyeongraekim commented on models/productDao.js
> +  const { category, sub_category, gender, limit, offset, sort } = filter
자바스크립트 내에서의 변수명 네이밍 컨벤션인 camelCase를 활용해서 subCategory의 변수명을 레이어 간 주고 받아주세요!

2023-02-14 12:43 UTC, kyeongraekim commented on services/productService.js
> +  productOptions.forEach((po) => {
웹서비스 개발 코드내에는 product 와 같은 정확한 명칭을 사용해주셔야 합니다! 해당 내용도 po와 같이 모호한 변수명을 탈피해주세요!

2023-02-14 14:39 UTC, ksh0123 commented on classes/product.js
> +  }
반영했습니다!
@jayhanjaelee

2023-02-14 14:41 UTC, ksh0123 commented on controllers/productController.js
> +const getDetails = catchAsync(async (req, res) => {
반영했습니다!

2023-02-14 14:44 UTC, ksh0123 commented on models/productDao.js
> +  const { category, sub_category, gender, limit, offset, sort } = filter
반영했습니다!
@jayhanjaelee

2023-02-15 00:33 UTC, ksh0123 commented on services/productService.js
> +  productOptions.forEach((po) => {
반영했습니다!
@jayhanjaelee

2023-02-15 01:40 UTC, kyeongraekim approved these changes
LGTM!~

2023-02-15 01:57 UTC, merged